services:
  server:
    build: ./
    command: flask --app ./src/server.py run --host=0.0.0.0
    ports:
      - 5000:5000
    env_file:
      - .env
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_volume:/root/.ollama
      - ./ollama_pull.sh:/ollama_pull.sh
    pull_policy: always
    tty: true
    restart: always
    entrypoint: ["/usr/bin/bash", "/ollama_pull.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  ollama_volume: